### ISSUE TITLE
Package Game Error

### ISSUE THREAD

**Issue by MrZorca** [Esri/vitruvio#107]
Hello,

When I try to package the game for windows I get the following error, is this error known to you and do you know how I can fix this?
`UATHelper: Packaging (Windows): ERROR: Expecting to find a type to be declared in a module rules named 'Vitruvio' in UE5Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.  This type must derive from the 'ModuleRules' type defined by Unreal Build Tool.
PackagingResults: Error: Expecting to find a type to be declared in a module rules named 'Vitruvio' in UE5Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.  This type must derive from the 'ModuleRules' type defined by Unreal Build Tool.`

When I add the Vitruvio plugin to the plugin folder of the project I get the following error upon creating the package:

`PackagingResults: Error: System.ArgumentException: An item with the same key has already been added. Key: Vitruvio`

**Comment by bneukom** [comment]
Hi @MrZorca. Thanks for reaching out! Wich Vitruvio version did you use when you got this error message?

**Comment by MrZorca** [comment]
Hi @bneukom, I am using version 1.2 on engine version 5.0.3. I might have fixed it by moving the Vitruvio plugin folder into the project locally instead of having it in the Engine's plugin folder. 
Because after that I was able to export it with good result.

**Comment by bneukom** [comment]
Thanks! I can reproduce it as well now. We will look into it. I'll let you know once we have a fix.

**Comment by bneukom** [comment]
Hi @MrZorca 

This `PackagingResults: Error: System.ArgumentException: An item with the same key has already been added. Key: Vitruvio` error actually happens if you have multiple Vitruvio installations (for example on in the Engine/Plugins/ folder and one in your Project or two in the Engine/Plugins folder).

But there was another problem with packaging as well. It should be fixed with the latest release https://github.com/Esri/vitruvio/releases/tag/v1.2.1

Thanks for bringing this to our attention!

Let me know if everything works now.

**Comment by bneukom** [comment]
I consider this as fixed. Please let us know if you still encounter any issues.
